- '! Command: show running-config'
- '! device: s1 (cEOSLab, EOS-4.34.2F-43232954.4342F.1 (engineering build))'
- '!'
- no aaa root
- '!'
- username admin privilege 15 role network-admin secret sha512 $6$1KQySH9LHkCKjyPK$fpL1LzsjKOtVIc8tZEVhLRoB2RnDCcnGJ63dfMYXZxA/rq26dhPvzML34ijCWMoj4GYV/fzeKmmVEHRzT4WgJ0
- '!'
- management api http-commands
- '   no shutdown'
- '!'
- no service interface inactive port-id allocation disabled
- '!'
- transceiver qsfp default-mode 4x10G
- '!'
- service routing protocols model multi-agent
- '!'
- hostname s1
- '!'
- snmp-server community public rw
- snmp-server host 10.0.100.1 version 2c public
- snmp-server enable traps
- '!'
- spanning-tree mode mstp
- '!'
- system l1
- '   unsupported speed action error'
- '   unsupported error-correction action error'
- '!'
- vlan 10,20,30,40
- '!'
- vlan 150
- '   name TransitVlan'
- '!'
- management api gnmi
- '   transport grpc default'
- '   !'
- '   transport grpc openmgmt'
- '      authorization requests'
- '   operation set persistence'
- '!'
- management api netconf
- '   transport ssh default'
- '!'
- interface Ethernet1
- '   switchport access vlan 10'
- '   ip access-group ssh in'
- '!'
- interface Ethernet2
- '   switchport access vlan 20'
- '   ip access-group ssh in'
- '!'
- interface Ethernet3
- '   no switchport'
- '   ip address 10.0.10.1/30'
- '   ipv6 address 2001:db8::/127'
- '   ip access-group ssh in'
- '   ipv6 ospf 15 area 0.0.0.0'
- '!'
- interface Ethernet4
- '   switchport mode trunk'
- '!'
- interface Ethernet10
- '   no switchport'
- '   ip address 10.0.100.8/24'
- '!'
- interface Management0
- '   ip address 172.20.20.14/24'
- '   ipv6 address 3fff:172:20:20::e/64'
- '!'
- interface Vlan10
- '   ip address 10.0.110.2/24'
- '   ip helper-address 10.0.10.14'
- '   vrrp 10 priority-level 250'
- '   vrrp 10 ipv4 10.0.110.1'
- '!'
- interface Vlan20
- '   ip address 10.0.120.2/24'
- '   ip helper-address 10.0.10.14'
- '   vrrp 20 priority-level 110'
- '   vrrp 20 ipv4 10.0.120.1'
- '!'
- interface Vlan30
- '!'
- interface Vlan150
- '   ip address 10.0.150.1/30'
- '!'
- ip access-list ssh
- '   10 deny tcp any any eq ssh'
- '   20 deny tcp any any eq telnet'
- '   30 permit ip any any'
- '!'
- ip routing
- '!'
- ipv6 unicast-routing
- '!'
- ip route 0.0.0.0/0 Ethernet3
- ip route 0.0.0.0/0 10.0.10.22
- '!'
- ipv6 route ::/0 3fff:172:20:20::1
- '!'
- router multicast
- '   ipv4'
- '      software-forwarding kernel'
- '   !'
- '   ipv6'
- '      software-forwarding kernel'
- '!'
- ipv6 router ospf 15
- '!'
- router rip
- '   network 10.0.10.0/30'
- '   network 10.0.110.0/24'
- '   network 10.0.120.0/24'
- '   network 10.0.150.0/30'
- '   no shutdown'
- '!'
- end
