- '! Command: show running-config'
- '! device: s3 (cEOSLab, EOS-4.34.2F-43232954.4342F.1 (engineering build))'
- '!'
- no aaa root
- '!'
- username admin privilege 15 role network-admin secret sha512 $6$IPd5oi1gYsJVztnq$0xuOZDtEwaDQRUd96s8vB1Tkd.DTdE7rUJShSJ6iNEmz6vglbJauIhclfwuRDpxuzs/9DWgI1GfwVoPY41rH70
- '!'
- management api http-commands
- '   no shutdown'
- '!'
- no service interface inactive port-id allocation disabled
- '!'
- transceiver qsfp default-mode 4x10G
- '!'
- service routing protocols model multi-agent
- '!'
- hostname s3
- '!'
- snmp-server community public rw
- snmp-server host 10.0.100.1 version 2c public
- snmp-server enable traps
- '!'
- spanning-tree mode mstp
- '!'
- system l1
- '   unsupported speed action error'
- '   unsupported error-correction action error'
- '!'
- management api gnmi
- '   transport grpc default'
- '   !'
- '   transport grpc openmgmt'
- '      authorization requests'
- '   operation set persistence'
- '!'
- management api netconf
- '   transport ssh default'
- '!'
- interface Ethernet1
- '   no switchport'
- '   ip address 10.0.10.18/30'
- '   ipv6 address 2001:db8::3/127'
- '   ip access-group ssh in'
- '   ipv6 ospf 15 area 0.0.0.0'
- '!'
- interface Ethernet2
- '   no switchport'
- '   ip address 10.0.10.37/30'
- '   ipv6 address 2001:db8::b/127'
- '   ip access-group ssh in'
- '   ipv6 ospf 15 area 0.0.0.0'
- '!'
- interface Ethernet3
- '   no switchport'
- '   ip address 10.0.10.21/30'
- '   ipv6 address 2001:db8::4/127'
- '   ip access-group ssh in'
- '   ipv6 ospf 15 area 0.0.0.0'
- '!'
- interface Ethernet10
- '   no switchport'
- '   ip address 10.0.100.2/24'
- '!'
- interface Management0
- '   ip address 172.20.20.3/24'
- '   ipv6 address 3fff:172:20:20::3/64'
- '!'
- ip access-list ssh
- '   10 deny tcp any any eq ssh'
- '   20 deny tcp any any eq telnet'
- '   30 permit ip any any'
- '!'
- ip routing
- '!'
- ipv6 unicast-routing
- '!'
- ip route 0.0.0.0/0 172.20.20.1
- '!'
- ipv6 route ::/0 3fff:172:20:20::1
- '!'
- router multicast
- '   ipv4'
- '      software-forwarding kernel'
- '   !'
- '   ipv6'
- '      software-forwarding kernel'
- '!'
- router ospf 10
- '   network 10.0.10.16/30 area 0.0.0.0'
- '   network 10.0.10.20/30 area 0.0.0.0'
- '   network 10.0.10.36/30 area 0.0.0.0'
- '   max-lsa 12000'
- '!'
- ipv6 router ospf 15
- '!'
- end
